// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwtlKTf-8rPpcwP2OGE7T2m-XYCd8GxLQ',
    appId: '1:130094613281:web:239c2baefb3acd83daf460',
    messagingSenderId: '130094613281',
    projectId: 'nusa-niaga-28262',
    authDomain: 'nusa-niaga-28262.firebaseapp.com',
    storageBucket: 'nusa-niaga-28262.firebasestorage.app',
    measurementId: 'G-QQHD4MN8PM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBly49sEC5OFcNyMC1GdfoW5wNEkIzlM04',
    appId: '1:130094613281:android:6b7450be94013ededaf460',
    messagingSenderId: '130094613281',
    projectId: 'nusa-niaga-28262',
    storageBucket: 'nusa-niaga-28262.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVZku0XItyKZYvvJ_XWjlrqJVUC50mO7Q',
    appId: '1:130094613281:ios:a70f1849df2e0f38daf460',
    messagingSenderId: '130094613281',
    projectId: 'nusa-niaga-28262',
    storageBucket: 'nusa-niaga-28262.firebasestorage.app',
    iosClientId: '130094613281-cl1g9eiv7dlsl50k5g67t4ki0s2gja7q.apps.googleusercontent.com',
    iosBundleId: 'com.example.nusaniaga',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVZku0XItyKZYvvJ_XWjlrqJVUC50mO7Q',
    appId: '1:130094613281:ios:a70f1849df2e0f38daf460',
    messagingSenderId: '130094613281',
    projectId: 'nusa-niaga-28262',
    storageBucket: 'nusa-niaga-28262.firebasestorage.app',
    iosClientId: '130094613281-cl1g9eiv7dlsl50k5g67t4ki0s2gja7q.apps.googleusercontent.com',
    iosBundleId: 'com.example.nusaniaga',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwtlKTf-8rPpcwP2OGE7T2m-XYCd8GxLQ',
    appId: '1:130094613281:web:e5d53a40bc838e54daf460',
    messagingSenderId: '130094613281',
    projectId: 'nusa-niaga-28262',
    authDomain: 'nusa-niaga-28262.firebaseapp.com',
    storageBucket: 'nusa-niaga-28262.firebasestorage.app',
    measurementId: 'G-HCPPJR6E7L',
  );
}
