// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEaJT7cAo0ViJ0VYkbu3eAnMAoh7EG7gU',
    appId: '1:716649970802:web:f1f155f053a793380b96eb',
    messagingSenderId: '716649970802',
    projectId: 'nusa-niaga',
    authDomain: 'nusa-niaga.firebaseapp.com',
    storageBucket: 'nusa-niaga.firebasestorage.app',
    measurementId: 'G-CS2ZLXDF4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKtxBKor8UShlFG115eKrg2Fi56EXe7AM',
    appId: '1:716649970802:android:38b580e178550e550b96eb',
    messagingSenderId: '716649970802',
    projectId: 'nusa-niaga',
    storageBucket: 'nusa-niaga.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuoVoM1zRQPbHNsFu9eqfOwc4Z8kEzdtg',
    appId: '1:716649970802:ios:5233feec92978c140b96eb',
    messagingSenderId: '716649970802',
    projectId: 'nusa-niaga',
    storageBucket: 'nusa-niaga.firebasestorage.app',
    iosBundleId: 'com.example.nusaniaga',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuoVoM1zRQPbHNsFu9eqfOwc4Z8kEzdtg',
    appId: '1:716649970802:ios:5233feec92978c140b96eb',
    messagingSenderId: '716649970802',
    projectId: 'nusa-niaga',
    storageBucket: 'nusa-niaga.firebasestorage.app',
    iosBundleId: 'com.example.nusaniaga',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEaJT7cAo0ViJ0VYkbu3eAnMAoh7EG7gU',
    appId: '1:716649970802:web:130460fec9d558390b96eb',
    messagingSenderId: '716649970802',
    projectId: 'nusa-niaga',
    authDomain: 'nusa-niaga.firebaseapp.com',
    storageBucket: 'nusa-niaga.firebasestorage.app',
    measurementId: 'G-ZMF6FR777K',
  );
}
